### ISSUE TITLE
Fonecta source doesn't update

### ISSUE THREAD

**Issue by specig** [omnight/phonehook#1]
Even I remove and reinstall it, it shows rev 4. I've updated Sailfish to 1.1.2.15, might this cause it?

**Comment by omnight** [comment]
Seems I forgot to update the revision number, but it should be the latest even if it says rev. 4. Is there any problem that you have experienced with it otherwise?

**Comment by specig** [comment]
Right after update said there no sources capable to search even Fonecta was working otherwise fine thus I made this report. After resetting and reinstalling everything works now like it should.

**Comment by omnight** [comment]
Yeah, the sources don't automatically update when the app is updated. I've changed the revision number now so it should be less confusing :)
