### ISSUE TITLE
Fonecta.fi Rev. 7 doesn't work

### ISSUE THREAD

**Issue by jonilam** [omnight/phonehook#11]
Fonecta.fi returns "no results" with every number. Search functionality doesn't work either with fonecta, it returns "Piilotettu nimi" (Hidden name) when searching name that can be found from fonecta.

**Comment by omnight** [comment]
Thanks for reporting, I am investigating.

**Comment by omnight** [comment]
I believe the missing results are the result of Fonecta requiring the user to agree to the updated EULA after login. I have added an error message now that the EULA needs to be accepted manually when this status is detected.

**Comment by jonilam** [comment]
That seemed to be the case. Tested and it is working. Thank you!
