### ISSUE TITLE
Add source for Spain

### ISSUE THREAD

**Issue by carmenfdezb** [omnight/phonehook#12]
Is possible to add http://www.abctelefonos.com for Spain? This source has search capability too.
Thank you in advance!!

**Comment by omnight** [comment]
Hi! I'm having a look at it now. It seems that not all functionality is available for all the countries, if I select Spain I loose the ability to do reverse number search. Doesn't seem to work if selecting "All Countries" and entering a full Spanish number either.

It would be possible to add it as a search-only source for Spain.

**Comment by carmenfdezb** [comment]
Ok, thank you very much!

**Comment by carmenfdezb** [comment]
For search only source is great, because there isn't sources for this feature in Spain

**Comment by omnight** [comment]
I have added it now, please give it a try! The site doesn't give different results if you search for people or businesses, seems to be a bug.

**Comment by carmenfdezb** [comment]
It seems there aren't results for some search. I wiil make more tests this weekend.
Thank you very much!!

**Comment by omnight** [comment]
Can you give me an example of a search that does not produce results?

**Comment by carmenfdezb** [comment]
Is possible to search only in Spain? This site give results for several countries.
On the other hand, here you are 2 examples that give no results:
1) Search People:
![pantalla1](https://cloud.githubusercontent.com/assets/6286776/12546629/628f3b50-c34b-11e5-9565-c5c0c8bd4ea0.JPG)
![screenshot-16-01-25-09-51-07](https://cloud.githubusercontent.com/assets/6286776/12546660/9898e020-c34b-11e5-99e0-c257a9c0ba77.png)
![screenshot-16-01-25-09-51-16](https://cloud.githubusercontent.com/assets/6286776/12546663/9c258694-c34b-11e5-85b1-8638bdcb8271.png)

2) Search Business:
![pantalla2](https://cloud.githubusercontent.com/assets/6286776/12546698/d5b0b136-c34b-11e5-8d7a-6bdf0d52cea0.JPG)
![screenshot-16-01-25-09-56-23](https://cloud.githubusercontent.com/assets/6286776/12546703/dd167b04-c34b-11e5-9461-c1e3c7ea5975.png)
![screenshot-16-01-25-09-56-33](https://cloud.githubusercontent.com/assets/6286776/12546704/dfbcef5a-c34b-11e5-8ac1-d094569deb2a.png)

**Comment by carmenfdezb** [comment]
Maybe it is because of accent, isn't it?

**Comment by omnight** [comment]
Yes, I think so. I have changed the encoding of URL parameters now, you can update and give it a try again.

**Comment by carmenfdezb** [comment]
Great!! It works fine!! Thank you very much!!

**Comment by omnight** [comment]
Alright, that's good to hear! I'm closing this now, but feel free to let me know if there are any other issues.
