### ISSUE TITLE
Google authentication is not working 

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#13]
Hi,

I starting noticing an error saying Google authentication required. I cleared the cache and signed in even after that it keeps saying  Google authentication required

**Comment by omnight** [comment]
Hi, it seems they have changed some stuff recently. I will have a look at it when I am able.

**Comment by adithyakhamithkar** [comment]
Thanks we are looking forward to it :)

**Comment by omnight** [comment]
I have put up a test version now. To try it you can enable "Test Sources" in settings and then download the bot again and log in with Google. My own Jolla is not working since the last firmware update, so I have some problems testing myself.

**Comment by adithyakhamithkar** [comment]
I did reset the data source and signed in again. It seems to be working now.

**Comment by omnight** [comment]
Alright, that sounds good. I have also updated the non-test version now to reflect the new login options.

**Comment by adithyakhamithkar** [comment]
Thanks a lot!

**Comment by dglent** [comment]
Yes it works again now, thanks !
