### ISSUE TITLE
Option to expire blocks automatically?

### ISSUE THREAD

**Issue by mikehgentry** [omnight/phonehook#14]
Hi!

Thanks so much for writing this, it's working really well.

Would it be possible to add an option to expire manually added blocks automatically? Presumably many scam numbers are turned over fairly quickly, and since numbers will be recycled and sometimes given to legitimate businesses / individuals, eventually you're going to hit false positives. Obviously I can manage this manually by clearing out my block list every so often, but I'd prefer it if I could set Phonehook to automatically delete a block after something like 6 months, and just re-add them as necessary.

Cheers!

**Comment by omnight** [comment]
Hello! Thanks for the suggestion, but I think very few people would find a use for this feature. If you want to attempt to add it in yourself, I can give you a few pointers on where to get started though!

**Comment by mikehgentry** [comment]
Thanks for the offer, though I doubt it'd help: I haven't written any C in
15 years, and never seriously tried C++.

I'll just delete them manually every so often.

Cheers.
