### ISSUE TITLE
True caller not working

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#15]
Hi,

Having an issue with true caller, This time authentication is working but true caller is not searching.

**Comment by omnight** [comment]
That is strange, I tested it now and it seems to work for me on the Android-port of the app (can't test on Jolla since my phone is bricked). Does it return no results for all numbers?

**Comment by adithyakhamithkar** [comment]
It's not returning the result for any numbers.

**Comment by omnight** [comment]
There are some things you can try:

- Test a number with full specified country-code, e.g. +911234567
- Clear the cache
- Try other sources, do any return results?

**Comment by adithyakhamithkar** [comment]
Yes I did try them cleared the cache only true caller is not working

**Comment by omnight** [comment]
Maybe you can try sending me the output of phonehook-daemon (in a PM) when you are attempting a lookup? Try these commands in terminal:

`killall phonehook-daemon
phonehook-daemon`

**Comment by adithyakhamithkar** [comment]
Done i just sent it to you.
