### ISSUE TITLE
Find logs

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#16]
Hi,

Can you please help me in finding the log file where the search are stored, I am looking for a number that I had searched but forgot to add it to my contacts.

Thanks,

**Comment by omnight** [comment]
Hi, that might be hard. There are no logs stored of searches that have been made, the only thing that is logged is the history of blocked calls.

If you called the number you might have an entry in the dialer app.

**Comment by adithyakhamithkar** [comment]
Hmmm nope i did not call just searched for and forgot about it.

Any ways thanks
