### ISSUE TITLE
Fonecta source rev.9 bot doesn't update

### ISSUE THREAD

**Issue by Termitebug** [omnight/phonehook#18]
Hello, I don't seem to get any EULA acceptance nor search results with correct login user data.
I have attached a log trace. I can reproduce this all time and clearing the cache doesn't help.
I'm using Jolla phone with 2.0.2.48 (Aurajoki).
[phonehook-fonectarev9bug.txt](https://github.com/omnight/phonehook/files/429980/phonehook-fonectarev9bug.txt)

**Comment by omnight** [comment]
Hi, thanks for the report. I've checked your log and it seems that I didn't escape quotes in the password properly, which has been fixed now (rev. 10). You might also want to change your password since it's clearly visible in the log file, but it helped me diagnose the issue.

**Comment by Termitebug** [comment]
Thanks for the note, I have to go change it asap :dash: It were left there accidentally :grey_question: 
Btw I have added Finnish translations to 'Translations' - closed thread, if you are interested :smiley:

![nayttokuva_20160822_001](https://cloud.githubusercontent.com/assets/11379204/17865451/4fe5b744-68ab-11e6-80b7-58646dbaa69f.png)

**Comment by omnight** [comment]
Thanks for the translation, I have added it now. Didn't use the translation of the app name though :)
