### ISSUE TITLE
0.3.1-1 installation failed

### ISSUE THREAD

**Issue by ahjolinna** [omnight/phonehook#2]
0.3.1-1 installation failed, here is the error output : http://pastebin.com/K2q45RaU

I'm using U11 (1.1.2.15)

**Comment by omnight** [comment]
Hi! Thanks for reporting this. I believe this is actually an issue with uninstalling 0.2.1 (or earlier) after the system has been updated. It was fixed in 0.3.0


If you check the comments on openrepos, there was another user with a similar problem. You can try to follow the steps I outlined there to uninstall the old version, and then you should be able to install 0.3.1

Let me know how it goes!

**Comment by ahjolinna** [comment]
nope uninstall did not help...same error

**Comment by omnight** [comment]
Were you able to uninstall the old version? There are a few console commands required to uninstall it when it gets in this state. What output does this command give?
```
> pkcon search name phonehook
```

**Comment by ahjolinna** [comment]
@omnight : is this enough info? http://pastebin.com/Tx5XXaKH

**Comment by omnight** [comment]
Yes, it seems like there is indeed an issue with uninstalling 0.2.1

I outlined the steps needed for uninstallation in this post: https://openrepos.net/comment/6088#comment-6088

>Make sure you have enabled developer mode (System > Settings > Developer Mode) and set a root password. Also enable Remote Connection. Open the terminal app, run these commands:
>
>```
>devel-su
>cd /usr/share/lipstick-jolla-home-qt5/
>patch -N -p4  < /usr/share/phonehook/phonehook-lipstick-v3.patch;
>pkcon remove phonehook
>```

After successful uninstallation there shouldn't be a problem with installing the new version.

**Comment by ahjolinna** [comment]
@omnight : yeah that worked thanks: http://pastebin.com/JZwY2R4x
btw. for your phonecall blocking feature, you could look at ScumStopper https://openrepos.net/content/ovekaaven/scumstopper

**Comment by ahjolinna** [comment]
small notice about running 3.1-1, I get this error : phonehook
error: XDG_RUNTIME_DIR not set in the environment.
[C] unknown:0 - Failed to create display (No such file or directory)

**Comment by omnight** [comment]
When does this error show up? Does the app crash somehow?

**Comment by ahjolinna** [comment]
that happened when I run it in root (devel-su), I did not notice -_-
but there was few errors when I run it normally, okay it does work : http://pastebin.com/2cze7rrx
I have OC  SailfishOS 1.1.2.16 update installed
