### ISSUE TITLE
Not working all att

### ISSUE THREAD

**Issue by mohdkukshi** [omnight/phonehook#20]
![screenshot_20160913_004](https://cloud.githubusercontent.com/assets/15812125/18472400/e4fd6ce8-79d4-11e6-9b1a-07262bbb478e.png)
![screenshot_20160913_003](https://cloud.githubusercontent.com/assets/15812125/18472416/03101dca-79d5-11e6-954d-52952cfc562e.png)

I installed phonehook and i installed data sources like truecaller and everycaller all but it does not does its job. It does not search any number nor from call log , nor if i enter number manually  , nor if i get any call i dont know whats the issue going on.
i am using intex Aqua Fish on version 2.0.2.51
![screenshot_20160913_002](https://cloud.githubusercontent.com/assets/15812125/18472278/07aa42bc-79d4-11e6-9471-dacc551c371e.png)
![screenshot_20160913_001](https://cloud.githubusercontent.com/assets/15812125/18472293/20e2cab0-79d4-11e6-916c-78f4d339528a.png)

**Comment by mohdkukshi** [comment]
Even when the sources says active and.up to date it does not does it job .please help me

**Comment by omnight** [comment]
Hi! First off not all sources support the "search" feature. That is meant to be used if you have a name and you want a number and not for doing a reverse lookup on a number.

If you want to look up a number manually, you can enter the call log and click on a number to look it up, or click on the source name on the main page and then use the pull menu to access the "Test Number" page.

By default, Phonehook will not show numbers that you already have in your contacts list, which may be why you have not seen the popup on incoming calls.

Hope that will help you.
