### ISSUE TITLE
Phonehook fails to work on Intex Aqua Fish

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#21]
Hi,

I just moved to the Intex Aqua Fish and I am running build 2.0.51

I think the phonehook is not comparable with this phone

And i am running phonehook in the debug mode and i get this output
`[nemo@Sailfish ~]$ phonehook-daemon
[D] main:50 - daemon starting?
[D] main:55 - open db
[D] QOfonoNetworkRegistrationInterface::getProperties:238 - "Method "GetProperties" with signature "" on interface "org.ofono.NetworkRegistration" doesn't exist
"
[D] auto_update::scheduleNext:48 - next update scheduled in 24261157 msecs
[D] main:64 - create listener
[D] dbus::dbus:17 - registering telepathy
[D] dbus_adapter::Instance:26 - new dbus_adapter
[D] dbus::gotModems:93 - found hardware modem at  "/ril_1"
[D] QWaylandEglClientBufferIntegration::QWaylandEglClientBufferIntegration:62 - Using Wayland-EGL
[D] MDesktopEntryPrivate::MDesktopEntryPrivate:230 - Specified Desktop file does not exist "/usr/share/applications/phonehook-daemon.desktop"
[W] unknown:46 - file:///usr/share/phonehook-daemon/qml/popup/HexGrid.qml:46: TypeError: Cannot read property '0,0' of undefined
[W] unknown:46 - file:///usr/share/phonehook-daemon/qml/popup/HexGrid.qml:46: TypeError: Cannot read property '0,0' of undefined
[D] phonenumber::phonenumber:12 - location prefix ""
[D] phonenumber::phonenumber:18 - no rule found
[D] phonenumber::phonenumber:12 - location prefix ""
[D] phonenumber::phonenumber:18 - no rule found`

Can you please help with a solution for this?

I am not sure if the other Jolla C users have this issue.

**Comment by omnight** [comment]
Hi, Maybe the Jolla C dual-SIM capability is causing some problems. I think it could be querying the wrong modem in your log (ril_1 instead of ril_0). Some code will probably have to be altered to account for the possible presence of a second SIM card. I don't have this device, so it will be a bit tricky to test things.

**Comment by adithyakhamithkar** [comment]
Currently I am running the SIM in the slot 1, Shall I try in slot 2?

You can let me know what test cases to run and how to do it. I'll try and help to debug.

**Comment by omnight** [comment]
Yes, you can try using the other slot and see if that does any difference. I will be able to look more at this next week and hopefully produce some test versions that I can send you.

**Comment by adithyakhamithkar** [comment]
Cool I'll try that and let you know.

Also look forward to the test cases.

Thanks,

**Comment by adithyakhamithkar** [comment]
It works on SIM2

**Comment by omnight** [comment]
Alright, then there is a workaround until I a new version sorted out.

**Comment by adithyakhamithkar** [comment]
Cool I'll look forward to it, Also do let me know if you want me to run any test cases.
