### ISSUE TITLE
Request for Adding Slovenian Phone Directories

### ISSUE THREAD

**Issue by corvinux** [omnight/phonehook#25]
Hi omnight, 

Would you be interested in adding Slovenian Phone Directories in your application sources.

There're 2 directories, which are probably somehow connected:

- Telefonski Imenilk Slovenije (Telephone Directory of Slovenia)  site:http://www.itis.si/

- Telekom Slovenije,  (which also use API or search engine of www.itis.si)  site: http://www.telekom.si/Imenik

Br,

Corvinux

**Comment by omnight** [comment]
Hi! I will have a look at this site next week, but it looks doable. Does any of these sites have an Android-app?

**Comment by omnight** [comment]
I've added a very basic version now, that will look up numbers of people calling. Let me know how it works

**Comment by corvinux** [comment]
Hi omnigh,
Tnx for your effort, but I'm sorry to say, I couldn't get even test search work.

**Comment by corvinux** [comment]
Hi omnigh again, 
After phone reboot, test search works, great.
