### ISSUE TITLE
request for chistachiamando.it (italian data source)

### ISSUE THREAD

**Issue by paolomi** [omnight/phonehook#27]
Hi :) Please add italian "chistachiamando.it" data source to block spammers. For example:  061050 is an italian spammer

http://www.chistachiamando.it/numero-telefono/061050

if in `<div class="description">` there is the word `negativa` then it's a spammer.

this example comes from yuri's comment at https://openrepos.net/content/ovekaaven/scumstopper
```
<service>
     <provider>Chi sta chiamando</provider>
     <type>blacklist</type>
     <request>http://www.chistachiamando.it/numero-telefono/</request>
     <personNameTag>//div[@class="description"]</personNameTag>
     <personNameExp>negativa</personNameExp>
   </service>
```

Many thanks. Bye :)

**Comment by omnight** [comment]
Hi! I've added it now, thanks for the detailed description.

**Comment by paolomi** [comment]
It works like a charm! :) many thanks (and sorry for the late answer)
