### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by eson57** [omnight/phonehook#3]
Hi,
Are you planning to update translation template? Or maybe you don' care about translations?

Btw... thanks for the nice app.

**Comment by omnight** [comment]
Hi! I haven't made localization possible yet, but it's something I might look into later.

**Comment by eson57** [comment]
Ok, thanks... then I might translate it later.  ;)

**Comment by omnight** [comment]
Localization is implemented now, so that (all?) texts can actually be translated and not just a handfull. I took your Swedish translation as base and expanded on it.

**Comment by eson57** [comment]
Thanks! I took a quick look and found at least one string, not so good translated. Don´t know who translated that, but I´ll correct it for you.  ;)

**Comment by omnight** [comment]
Thanks. Just noticed that I forgot to commit the translation files for the daemon. These contain translations for headers in the popup, such as "name", "address" and so on. I added them now.

**Comment by eson57** [comment]
Hmm... what file version are we talking about? I'm looking at 0.6.0-2. and it says "3 hours ago".

**Comment by omnight** [comment]
The files located in /client/daemon/translations/

**Comment by eson57** [comment]
Ok, I don't know whose toes I step on now, but I did change some strings into imho, better/correct Swedish. Use it or not? That is your decision.  ;)

**Comment by Termitebug** [comment]
Hi, I have Finnish translations (daemon + gui) for you to use if you decide to add it.
I noticed from translation source code that we can translate the app name.
In finnish app could be called 'puhelinkoukku' (phonehook.desktop ; Name[fi]=puhelinkoukku).

[gui-phonehook-fi.txt](https://github.com/omnight/phonehook/files/430752/gui-phonehook-fi.txt)
[daemon-phonehook-fi.txt](https://github.com/omnight/phonehook/files/430753/daemon-phonehook-fi.txt)
