### ISSUE TITLE
No results from Spanish sources

### ISSUE THREAD

**Issue by carmenfdezb** [omnight/phonehook#32]
Spanish sources doesn't show any results when I search a phone number.
For example, Listaspam.com:

![photo_2017-11-15_08-21-51](https://user-images.githubusercontent.com/6286776/32823815-c77f40dc-c9de-11e7-9b34-0ee2e0c8c376.jpg)

![photo_2017-11-15_08-22-08](https://user-images.githubusercontent.com/6286776/32823816-c7a8b0e8-c9de-11e7-872d-46cef6bbd5da.jpg)
(https://www.listaspam.com/busca.php?Telefono=912048500)

This same issue is in Telefonspam.es

**Comment by omnight** [comment]
Hi, sorry for late reply.

I am a bit behind in maintaining the lookup sources, but I tried that number on Listaspam and I do get the expected results. I'm not sure why it's not working for you.

Can you try clearing the cache and doing a retry?

**Comment by carmenfdezb** [comment]
Thanks, @omnight!! I've cleared the cache and now the info about the phone number is showed:
![captura_20171120_001](https://user-images.githubusercontent.com/6286776/33031663-3998cfc8-ce1f-11e7-807f-2da8aac6fa68.png)
