### ISSUE TITLE
Fontsize and light themes

### ISSUE THREAD

**Issue by a-dekker** [omnight/phonehook#48]
Some parts of the interface have very small fonts on devices with high screen resolutions.

Also, it doesn't take light themes in consideration very well.

Could you have a look at that? If you don't want to spend time on this, I could try to create a PR for you addressing these points.

**Comment by arminfelder** [comment]
sorry for the late response, I am quite short on time at the moment...
If you would manage to fix the issue, I would be happy to review/merge it

**Comment by a-dekker** [comment]
See https://github.com/omnight/phonehook/pull/49
