### ISSUE TITLE
Search results are incorrectly binded under one name by postal code.

### ISSUE THREAD

**Issue by specig** [omnight/phonehook#5]
When using Fonecta results are binded under one name per postal code and occasionally gives wrong address for the name. In attached screenshot only search term was lastname Akola in What? -field. 
![tmp_12442-screenshot-27-07-15-22-54-58-502532871](https://cloud.githubusercontent.com/assets/10297317/8916493/9feda07a-34b4-11e5-9148-e042f96bdf8b.png)

**Comment by omnight** [comment]
Hi! Thanks for reporting.
I've put up a new version of fonecta (version 7) that should fix this problem, I also fixed a few other small issues I noticed.

**Comment by specig** [comment]
Hi.
Thank you, now it works like it should. :+1:

**Comment by omnight** [comment]
Great! Parsing can easily break when they update the site, so just let me know if you find more issues later on.
