### ISSUE TITLE
No edit function on Call Blocks page

### ISSUE THREAD

**Issue by a-dekker** [omnight/phonehook#56]
I wanted to change the description of a blocked call, and the edit icon (pencil) suggest that I could do that, but there is no way to change the name. You have to delete the entry and look it up in the history, so that you can add it using another name.

Could this suggested edit function be added?

**Comment by a-dekker** [comment]
As there is not much happening out here I decided to give it a go myself: https://github.com/omnight/phonehook/pull/67

**Comment by arminfelder** [comment]
Fixed by #67
