### ISSUE TITLE
Truecaller not working

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#7]
Truecaller data source is not working I tried clearing the cache and logged in again. I just get a response saying "No results found"

**Comment by omnight** [comment]
Hi, are you using the version called just "Truecaller" in the app? This version has been updated with both FB and Google login, which one of them are you using?

I tested it just now and logged in with FB before making a search, and got results back.

**Comment by adithyakhamithkar** [comment]
Yes i am using the one called just truecaller and i am logged in using google. It was working all these days just from yesterday it's not working. All of a sudden it stopped.

I just tried both. Reset the truecaller source and reinstall the phonehook. Still i am getting the same error No result found.
![20150826195543](https://cloud.githubusercontent.com/assets/3615342/9497950/0dd96276-4c35-11e5-8e6d-152efc3a3859.png)

**Comment by omnight** [comment]
I tried the google login method now, and I am getting the same result as you. I will try to debug a bit to see what is going wrong. Facebook login still seems to be working.

**Comment by adithyakhamithkar** [comment]
Thanks appreciate it!

**Comment by omnight** [comment]
Hi again, I have put up a new version of the truecaller now. It seems they had updated the layout. Give it a try!

**Comment by adithyakhamithkar** [comment]
I updated to the Revision No. 2 works now!

Thanks a lot for you quick response and fix, This app is a life line for a few.

**Comment by omnight** [comment]
Great that it works, I'm closing this issue now.
