### ISSUE TITLE
Feature request

### ISSUE THREAD

**Issue by adithyakhamithkar** [omnight/phonehook#8]
Hi,

I would like a make a feature request. In call logs, Can we have dialed, received along with missed calls?

I would be really nice if we could have this.

Thanks,

**Comment by omnight** [comment]
Hi, this should be easy enough to add. I'll put it on my todo-list.

**Comment by adithyakhamithkar** [comment]
Thanks a lot I'll look forward to it.

Also It would be nice if you could share your todo-list that would be a road map for this app.

**Comment by omnight** [comment]
I don't have much in it. Only planned feature is being able to save a search result as a contact in the phone. I have been thinking about adding navigation button to the caller popup as well, just need to standardize the result fields first.

**Comment by adithyakhamithkar** [comment]
Thanks
